project:
  type: website
  output-dir: docs
  
website: 
  title: Srishti Ramanathan
  description: A website built with Quarto
  navbar:
    title: Srishti Ramanathan
    left:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog/index.qmd 
      - text: About
        href: about.qmd
  page-footer:
    left: &#169; 2025 Srishti Ramanathan
    right: Made with [Quarto](https://quarto.org)
    
format: 
  html:
    theme: lux

execute:
  freeze: true
  